doctrine_migrations_multiple_database:
  entity_managers:
    main:
      migrations_paths:
        DoctrineMigrations\Main: '%kernel.project_dir%/migrations/Main'
    second:
      migrations_paths:
        DoctrineMigrations\Second: '%kernel.project_dir%/migrations/Second'
