parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''
  env(DATABASE_URL_SECOND): ''

doctrine:
  dbal:
    default_connection: main
    connections:
      main:
        url: '%env(resolve:DATABASE_URL)%'
        default_table_options:
          charset: utf8
          collate: utf8_unicode_ci
      second:
        url: '%env(resolve:DATABASE_URL_SECOND)%'
        default_table_options:
          charset: utf8
          collate: utf8_unicode_ci

  orm:
    auto_generate_proxy_classes: true
    default_entity_manager: main
    entity_managers:
      main:
        connection: main
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          App:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Main'
            prefix: 'App\Entity\Main'
            alias: App
      second:
        connection: second
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
          Second:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity/Second'
            prefix: 'App\Entity\Second'
            alias: Second

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'