parameters:
  app.path.category_images: /images/category

vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    category_images:
      uri_prefix: /images/category
      upload_destination: '%kernel.project_dir%/public/%app.path.category_images%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
