<?php
$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('config')
    ->exclude('var')
    ->exclude('public/bundles')
    ->exclude('public/build')
    // exclude files generated by Symfony Flex recipes
    ->notPath('bin/console')
    ->notPath('public/index.php')
;

// https://cs.symfony.com/doc/rules/
return (new PhpCsFixer\Config)
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'blank_line_after_opening_tag' => false,
        'linebreak_after_opening_tag' => true,
        'lowercase_cast' => false,
        'mb_str_functions' => true,
        'native_function_invocation' => false,
        'native_constant_invocation' => false,
        'new_with_braces' => false,
        'no_php4_constructor' => true,
        'no_unreachable_default_argument_value' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'ordered_class_elements' => [], // Remove 'use_trait'
        'ordered_imports' => true,
        'phpdoc_summary' => false, // In comments: add useless "." at ending and make urls in error
        'php_unit_strict' => true,
        'phpdoc_order' => true,
        'semicolon_after_instruction' => true,
        'single_blank_line_before_namespace' => false,
        'single_import_per_statement' => false,
        'single_trait_insert_per_statement' => false,
        'strict_comparison' => true,
        'strict_param' => true,
    ])
    ->setFinder($finder)
    ->setCacheFile(__DIR__.'/var/cache/.php_cs.cache')
    ;
